[build]
  publish = "public"
  functions = "netlify/functions"

# Redirections spécifiques pour l'authentification
[[redirects]]
  from = "/api/auth/discord"
  to = "/.netlify/functions/auth-discord"
  status = 302

[[redirects]]
  from = "/api/auth/callback"
  to = "/.netlify/functions/auth-callback"
  status = 200

[[redirects]]
  from = "/api/auth/logout"
  to = "/.netlify/functions/auth-logout"
  status = 302

[[redirects]]
  from = "/api/auth/me"
  to = "/.netlify/functions/auth-me"
  status = 200

# Redirections pour les autres API
[[redirects]]
  from = "/api/get-tickets"
  to = "/.netlify/functions/get-tickets"
  status = 200

[[redirects]]
  from = "/api/get-ticket-details"
  to = "/.netlify/functions/get-ticket-details"
  status = 200

[[redirects]]
  from = "/api/claim-ticket"
  to = "/.netlify/functions/claim-ticket"
  status = 200

[[redirects]]
  from = "/api/admin/grant-access"
  to = "/.netlify/functions/admin-grant-access"
  status = 200

[[redirects]]
  from = "/api/sync-tickettool-v2"
  to = "/.netlify/functions/sync-tickettool-v2"
  status = 200

[[redirects]]
  from = "/api/webhook/discord"
  to = "/.netlify/functions/webhook-discord"
  status = 200

# Routes d'administration (super admin uniquement)
[[redirects]]
  from = "/api/admin/list-users"
  to = "/.netlify/functions/admin-list-users"
  status = 200

[[redirects]]
  from = "/api/admin/add-user-by-id"
  to = "/.netlify/functions/admin-add-user-by-id"
  status = 200

[[redirects]]
  from = "/api/admin/update-user"
  to = "/.netlify/functions/admin-update-user"
  status = 200

[[redirects]]
  from = "/api/get-roles"
  to = "/.netlify/functions/get-roles"
  status = 200

# Route : Liste des utilisateurs staff pour l'assignation
[[redirects]]
  from = "/api/get-staff-users"
  to = "/.netlify/functions/get-staff-users"
  status = 200

# Route : Correction des catégories
[[redirects]]
  from = "/api/admin/fix-categories"
  to = "/.netlify/functions/admin-fix-categories"
  status = 200

# Route : Mise à jour de la priorité d'un ticket
[[redirects]]
  from = "/api/update-ticket-priority"
  to = "/.netlify/functions/update-ticket-priority"
  status = 200

# ✅ NOUVELLE ROUTE : Marquer tous les tickets comme lus
[[redirects]]
  from = "/api/mark-all-as-read"
  to = "/.netlify/functions/mark-all-as-read"
  status = 200

# ✅ NOUVELLE ROUTE : Archiver les anciens tickets
[[redirects]]
  from = "/api/archive-old-tickets"
  to = "/.netlify/functions/archive-old-tickets"
  status = 200

# ✅ NOUVELLE ROUTE : Récupérer les tickets archivés
[[redirects]]
  from = "/api/get-archived-tickets"
  to = "/.netlify/functions/get-archived-tickets"
  status = 200

# ✅ NOUVELLE ROUTE : Activer/désactiver le vote sur un ticket
[[redirects]]
  from = "/api/toggle-voting"
  to = "/.netlify/functions/toggle-voting"
  status = 200

# Redirection SPA - doit être en dernier
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
